networks:
  erp:
    name: erp
    driver: bridge

services:
  erp-app:
    image: v7lvet-erp:latest
    container_name: erp-app
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CONVEX_URL=https://tangible-curlew-143.eu-west-1.convex.cloud
      - NEXT_PUBLIC_CONVEX_SITE_URL=https://tangible-curlew-143.eu-west-1.convex.site
      - BETTER_AUTH_SECRET=Mr5O1K+63oAD5WJNvXZfVhQPk9IBWbIODbuOFsR4pIg=
      - BETTER_AUTH_URL=http://82.29.174.221:3001
      - NEXT_PUBLIC_BETTER_AUTH_URL=http://82.29.174.221:3001
    networks:
      - erp
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
